browser = chrome
testEnvironment = https://automationexercise.com/
invalidEmail = aaaaaaaaaaa@gmail.com
invalidPassword = Wwwweertty@123
name = VigneshTest01
validEmail = vigneshtest01@gmail.com
validPassword = Welcome@123
firstName = Vignesh
lastName = Annamalai
company = abcxyz1
address1 = abcxyz1
address2 = abcxyz1
state = abcxyz1
city = abcxyz1
zipcode = 111111
mobileNumber = 1111111111
getInTouchSubject = This is the sample subject.
getInTouchMessage = This is the sample message.
getInTouchUploadFile = E:\\Automation_Testing\\Selenium\\AutomationPracticeProject\\src\\main\\resources\\testdata\\file.txt
productId = 1
